### PR TITLE
Add autoCloseable field to ApiTypeInfo and corresponding tests

### PR DESCRIPTION
**Pull request by krishnarb3**
Signed-off-by: Rb Krishna <krishnarb3@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
it needs to work with `java.lang.AutoCloseable`

**Comment by krishnarb3** [comment]
I was having the same doubt. Can you let me know how I can do that, I'm a bit new to the vertx-codegen project 😅

**Comment by vietj** [comment]
it seems quite obvious that you need to use `java.lang.AutoCloseable` as type

**Comment by vietj** [comment]
are you going to finish this PR or should we close it right away ?

**Comment by vietj** [comment]
have you signed the Eclipse Contributor Agreement @krishnarb3 ?

**Comment by vietj** [comment]
@krishnarb3 actually we should have this on `ClassTypeInfo` and not `ApiTypeInfo`

**Comment by vietj** [comment]
but I think for now it will be ok

**Pull request merged**
