### PR TITLE
Fix #131

### LINKED ISSUE #131: Unable to handle DataObject using annotations on fields
On recent OpenJDK, the processing of a data object having a field with an annotation leads to:

```
SEVERE: Could not generate element for io.vertx.example.spring.worker.Book: null
java.lang.UnsupportedOperationException
	at java.util.AbstractCollection.add(AbstractCollection.java:262)
	at io.vertx.codegen.DataObjectModel.lambda$processMethods$7(DataObjectModel.java:324)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
```

### PR DESCRIPTION
**Pull request by cescoffier**
Replace the call failing on OpenJDK.

### CODE REVIEW

**Comment by vietj** [comment]
looks weird but well :-)

**Comment by cescoffier** [comment]
I agree... Fortunately, one example caught it.

**Comment by tsegismont** [comment]
That would be worth an OpenJDK bug report, I think ;-)

2017-06-26 15:26 GMT+02:00 Clement Escoffier <notifications@github.com>:

**Comment by cescoffier** [comment]
Actually, I'm not sure it's really due to OpenJDK. It didn't work on OpenJDK, but then I was able to reproduce it on Oracle JDK.

**Pull request merged**
