### PR TITLE
Support for loading custom GeneratorLoader and Generator using ServiceLoader

### PR DESCRIPTION
**Pull request by okou19900722**
Support for loading custom GeneratorLoader and Generator using ServiceLoader

### CODE REVIEW

**Comment by vietj** [comment]
loooks great

**Comment by okou19900722** [comment]
thanks, i will try to Rewrite vertx-lang-kotlin generator without MVEL

**Comment by vietj** [comment]
@okou19900722 that would be great, fortunately it's not a complicated generator (unlike rx)

**Comment by okou19900722** [comment]
Yes, there is a saying in China: "循序渐进," which means Step by step

**Comment by vietj** [comment]
that's a universally good principle :-)

**Comment by okou19900722** [comment]
#186 fixed a bug
#187 Converting `common-lib` in mvel templ to `CodeGenHelper` in java
I have completed kotlin's generator, but need to merge the two pr, then I can push a pr to `vertx-lang-kotlin-codegen`

**Pull request merged**
