### PR TITLE
Add equals & hashCode helper methods for DataObjectConverter

### PR DESCRIPTION
**Pull request by fzakaria**
Add equals & hashCode helper methods for generated DataObject annotated classes.

Signed-off-by: Farid Zakaria <farid.m.zakaria@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
@fzakaria can you test this with vertx-core options which has existing tests for equals ?

**Comment by vietj** [comment]
@fzakaria what is the current status of this PR ?

**Comment by fzakaria** [comment]
It should be ready for review -- I ran it on vert.x-core and everything built fine.

Nothing is using the new DataConverter equals/hashcode yet though as the SNAPSHOT is not released yet.

**Comment by vietj** [comment]
@fzakaria makes sense, I'll review this one first

**Comment by vietj** [comment]
the generated code should follow Vert.x convention and thus equals shoud use curly braces for the `if` statement

**Comment by vietj** [comment]
in the equals expression, the first sub-expression of the `... && ...` expression should be on the same line than the `return` statement.

**Comment by fzakaria** [comment]
@vietj made the changes you requested.

**Pull request merged**
