### PR TITLE
Jsonifiable model

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Issue https://github.com/vert-x3/vertx-codegen/issues/235

This PR adds:

- JsonCodec, JsonEncoder, JsonDecoder interfaces
- Support for defining JsonCodec inside ModuleGen annotation 
- Jsonifiable type mirror created from TypeMirrorFactory
- Support for jsonifiable types into data objects and class models

## Usage
Users that wants to declare a json codec must create a class that implements `JsonCodec` interface: https://github.com/vert-x3/vertx-codegen/compare/jsonifiable_model?expand=1#diff-457be30f1f4f02639556670b778ecb45 . This class must be concrete with an empty constructor
Then to use it in their packages they need to specify it in `ModuleGen` annotation: https://github.com/vert-x3/vertx-codegen/compare/jsonifiable_model?expand=1#diff-ab635da43034f2860d951efc5b1d30fe

## Impacts
Now codegen users must be aware that when they process a method parameter or a return type they can have a new type: `JsonifiableType`. This type contains a `ClassTypeInfo` that specifies the codec.
TypeMirrorFactory now is context-aware. It takes as constructor parameter the PackageElement of the model that is going to use it. Both `ClassModel` and `DataObjectModel` has a method called `getReferencedJsonifiableTypes()` that returns all jsonifiable types used inside the model

### CODE REVIEW

**Comment by vietj** [comment]
as far as I understand this PR supports any JSON element which are object,array, string, number and boolean right ?

**Comment by slinkydeveloper** [comment]
Yep as we discussed the JsonCodec interface does Object <-> T, where Object is a Vert.x Json Type

**Comment by vietj** [comment]
I think we want to try to unify the existing ClassKind that we have today which are BASIC, JSON_ARRAY and JSON_OBJECT with the new one you added to make the model more coherent. The point being that such types are jsonifiable with the trivial conversion.

**Comment by slinkydeveloper** [comment]
I thought the same with DataObject kind. But the jsonifiable type has an associated json codec, while for data object the conversion is well defined by the data object contract, so code generators can make assumptions on it. I can't see a way to unify these types without breaking the existing code generators.

**Comment by vietj** [comment]
I think also we want the JSON codec class declared in the package `io.vertx.core.json` as they will live here as they are needed at runtime.

**Comment by vietj** [comment]
I think also we just want JsonCodec class and we don't need to have Encoder/Decoder super interfaces.

**Comment by vietj** [comment]
I don't think we want a JsonIfiableType, as the types represent actually the java lang model classes

**Comment by slinkydeveloper** [comment]
They don't represent the java lang classes, they represent the "custom" types that they can be converted with a codec into json types

**Comment by slinkydeveloper** [comment]
> I think also we want the JSON codec class declared in the package `io.vertx.core.json` as they will live here as they are needed at runtime.

So I should put it both in core and here in codegen?

**Comment by slinkydeveloper** [comment]
This idea is very similar to how DataObject is implemented: code generator implementors expects a type info `DataObjectTypeInfo` that they can handle in a proper way.

**Comment by vietj** [comment]
yes both in core dans codegen but we will do core later, for now we are focusing on the model :-)

**Comment by vietj** [comment]
@slinkydeveloper I would like to try to unify the json conversion thing so that's why it should not appear in the TypeInfo hierarchy as a type but rather as a composition.

**Comment by vietj** [comment]
I think we can write rather an RFC in the wiki with the current state and work in this document rather on the PR ? (like on a whiteboard)

**Comment by vietj** [comment]
for DataObject the codec is JSON constructor + toJSON() method

**Comment by slinkydeveloper** [comment]
> for DataObject the codec is JSON constructor + toJSON() method

Ok but there is no real concrete json codec implementation for each data object, I initially started with the idea to create the hierarchy `ClassTypeInfo` <- `JsonifiableTypeInfo` <- `DataObjectTypeInfo` but it's not possible. `JsonifiableTypeInfo` has a ref to a concrete json codec implementation, that doesn't exist for `DataObjectTypeInfo`

> @slinkydeveloper I would like to try to unify the json conversion thing so that's why it should not appear in the TypeInfo hierarchy as a type but rather as a composition.

As far as I understood a suitable solution for you could be unify DataObjectTypeInfo and JsonifiableTypeInfo into same thing. Kind and nullity of json codec ref can be used to distinguish between these two

Or another solution (imo cleaner but more breaking) could be: decouple the type tree from json encoding/decoding stuff. We create another object (that contains json codecs) and is capable to understand if a ClassTypeInfo is jsonifiable because is a json primitive, a data object or a class with a codec. And this class is able to provide you the codec if needed. This could also be useful if someone needs to extend this class for specific generators that can support other types

**Comment by vietj** [comment]
Indeed I don't want to have jsonifiable as part of the hierarchy.

We do  have a hierarchy of types and each type might or not be converted to JSON.

We retrofit the ClassKind.basic boolean to ClassKind.json and say that ClassKind.JSONIFIABLE has also json=true.

When a generator finds a ClassKind with json=true then if that's JSONIFIABLE then the corresponding converter can be looked up on the ModuleInfo that expose a lookup operation that returns the type of the codec to use for a given TypeInfo object.

**Comment by slinkydeveloper** [comment]
I removed `JsonifiableTypeInfo` and moved the parsed json codecs inside `ModuleInfo`. @vietj wdyt?

**Comment by pmlopes** [comment]
Some notes from my side:

* Usually I'd expect to read `Jsonable` instead of `Jsonifiable` (i'm no linguistic but sounds better to me imho, feel free to disagree)
* Would this replace the need for the JSON mapper? (probably not as we cannot guarantee to know all JSON schemas ahead of time)
* This only converts from POJO to DataObject, not to String/Buffer or vice versa. I expect JSONCodec to be used to encode/decode either over the eventbus or the network, so my question is why the middle step? why not go from POJO to String/Buffer directly?

**Comment by slinkydeveloper** [comment]
>     * Usually I'd expect to read `Jsonable` instead of `Jsonifiable` (i'm no linguistic but sounds better to me imho, feel free to disagree)

Agree

>     * Would this replace the need for the JSON mapper? (probably not as we cannot guarantee to know all JSON schemas ahead of time)

No, this codecs will be used by codegen to allow any type inside interfaces. In theory in the generated code they are called to do encoding/decoding. I think that probably users are going to use the json mapper (of her choice) to implement these json codecs. 

>     * This only converts from POJO to DataObject, not to String/Buffer or vice versa. I expect JSONCodec to be used to encode/decode either over the eventbus or the network, so my question is why the middle step? why not go from POJO to String/Buffer directly?

This does every Java type (also jdk types like ZonedDateTime) to a vertx json type (primitives, json object and json array) and viceversa

**Comment by slinkydeveloper** [comment]
I have a couple of proposals

### JsonCodec
JsonCodec interface must have two generics: TARGET_TYPE and JSON_TYPE. This is because of method overloading checks and It helps codegens to know what Json type are expecting (e.g. in js lang codegen the `Java.asJSONCompatible()` returns a boxed primitive or a Map/List and these two must be converted to JsonObject/JsonArray before calling the codecs).

The codecs must be instantiated by the generated code. However, if we want to simplify it allowing codegen implementors to just call a static instance, we can generate for each codec a simple instance holder. I'm not prone to add to JsonCodec contracts a rule that users must add the instance and instance holder.

### DataObject
We change the purpose of the data objects: from now on they must be used only for automatic generation of converter. We can also remove the restrictions about constructor and toJson method. 

The point is: If you want to write encode/decode logic you must use codecs, if you want to autogenerate the converter you must use data object.

DataObject converters will implement JsonCodec and they are automatically added to Jsonable types. No more distinction between these two.

If you want to customize the DataObject conversion logic you can do one of these two:
* you add codecs for its fields (not inside DataObject annotation but always inside ModuleGen annotation)
* you flag the DataObject to don't generate a converter that implements jsoncodec, so you manually write the encode/decode code calling the generated converter.

But remember, a converter **is always** generated, otherwise there is no purpose of using data objects  

### Type mirrors tree
All types that has codecs will be mirrored as JsonifiableClassInfo (That I will rename as Jsonable). JsonableClassInfo contains the JSON_TYPE mirror and the codec mirror. I want to totally avoid putting all codec retrieval logic around the classmodel/codegen logic. IMHO I think that fitting it in type tree simplifies the usage of codegen apis, as now codegen implementors just expect a jsonable type that describes everything of it

In ClassModel the JsonableTypes are collected during traversal, so codegen can easily iterate through them to instantiate the required codecs 

DataObjectClassInfo and DataObject class kind disappears. A DataObject with converter that implements jsoncodec is classified as JsonifiableClassInfo

I think that for lang implementors the required tasks to adapt these changes are: instantiate the codecs and convert the logic that uses DataObject to logic that uses Jsonable types. It should be pretty straightforward, unless there is something that I don't know :smile:

**Pull request closed without merging**
