### PR TITLE
A fix for the issue #295

### PR DESCRIPTION
**Pull request by cvgaviao**
Signed-off-by: Cristiano V. Gavião <cvgaviao@gmail.com>

A fix for #295

### CODE REVIEW

**Comment by cvgaviao** [comment]
@vietj, may I ask you to review this PR?

**Comment by vietj** [comment]
did you check this works with generators vertx-rx or service-proxy ?

**Comment by cvgaviao** [comment]
> did you check this works with generators vertx-rx or service-proxy ?

Well, we are not using vertx-rx, but we are using service-proxy and vertx-web-api-service intensively in our project.
Are there tests specifically for them?

**Comment by vietj** [comment]
did you try if it works with service-proxy ?

**Comment by cvgaviao** [comment]
> did you try if it works with service-proxy ?

Well, with DataObject it is 100%, but with service-proxy not entirely. Only when returning the enum. If I use the enum as parameter, it is not using the Converter :(
I've created this:
```
    Future<String> testEnum(RunMode mode);
    Future<RunMode> testEnum2(String mode);
```
and the resulted methods are:
```
        case "testEnum2": {
          service.testEnum2((java.lang.String)json.getValue("mode")).onComplete(res -> {
                      if (res.failed()) {
                        HelperUtils.manageFailure(msg, res.cause(), includeDebugInfo);
                      } else {
                        msg.reply(res.result() != null ? br.com.c8tech.mmarket.backend.models.JsonConverters.serializeRunMode(res.result()) : null);
                      }
                   });
          break;

```
        case "testEnum": {
          service.testEnum(json.getString("mode") == null ? null : br.com.c8tech.mmarket.backend.models.RunMode.valueOf(json.getString("mode"))).onComplete(HelperUtils.createHandler(msg, includeDebugInfo));
          break;
        }
```

```

**Comment by cvgaviao** [comment]
@vietj, do you have any clue about what I've missed ?

**Comment by vietj** [comment]
I don't know, that need to be studied

**Comment by cvgaviao** [comment]
> I don't know, that need to be studied

I'm thinking that the problem is in the `io.vertx.serviceproxy.generator.ServiceProxyGen` class. More specifically in the `io.vertx.serviceproxy.generator.ServiceProxyGen.generateAddToJsonStmt(ParamInfo, CodeWriter)` method. It doesn't check about converters there.

**Comment by cvgaviao** [comment]
> I don't know, that need to be studied

The issue that I found is definitively on `io.vertx.serviceproxy.generator.ServiceProxyHandlerGen.generateJsonParamExtract(ParamInfo)`

**Comment by vietj** [comment]
can you check also vertx-rx ? I think the same would apply

**Comment by cvgaviao** [comment]
> can you check also vertx-rx ? I think the same would apply

Well, I don't use and don't know about this module. But I cloned and searched for enum references. I just found references on some TCK related classes...

Btw, how are those tck classes supposed to work?

**Comment by vietj** [comment]
TCK classes are created in this project and then generated in other projects with some tests to check it works according to expectations. Indeed we need something in TCK to test your new behavior.

**Comment by cvgaviao** [comment]
> TCK classes are created in this project and then generated in other projects with some tests to check it works according to expectations. Indeed we need something in TCK to test your new behavior.

I think I did what was in my possibilities already...

**Comment by cvgaviao** [comment]
Hey @vietj, is there anything more I can do for you in this PR? I think I've already created the TCK tests that you referred and I've got no errors while building RX.

**Comment by vietj** [comment]
@cvgaviao we need implementations for vertx-rx, vertx-lang-kotlin-coroutines and vertx-service-proxy

**Comment by cvgaviao** [comment]
well, I already provided a PR for vertx-service-proxy.  I have not seen
anything any need on vertx-rx, besides the tck that I've already did. :-(

wouldn't you take care of the vertx-lang-kotlin-coroutines in another time?

**Comment by cvgaviao** [comment]
Hi @vietj. You didn't give me any feedback about all those related PRs.
So, are you going to accept them?  Because if you won't, I must research another way to deal with my customer's data.

**Comment by vietj** [comment]
@cvgaviao can you provide a new PR with a single commit and sign it along with the Eclipse Contributor Agreement ?

**Comment by vietj** [comment]
I would like to get this handled soon.

**Comment by cvgaviao** [comment]
> @cvgaviao can you provide a new PR with a single commit and sign it along with the Eclipse Contributor Agreement ?

@vietj I have no free time to look at this in the next weeks.

**Comment by vietj** [comment]
@cvgaviao I just need you to merge all the existing commits in a single commit and sign the Eclipse Contributor Agreement and sign the commit , no code change is required

**Comment by cvgaviao** [comment]
> @cvgaviao I just need you to merge all the existing commits in a single commit and sign the Eclipse Contributor Agreement and sign the commit , no code change is required

@vietj, I'm in a hurry here.  But I'll do this tomorrow.

**Comment by cvgaviao** [comment]
I'm closing this forgotten branch and I going to add a new one.

**Pull request closed without merging**
