### PR TITLE
Add support for different naming conventions to DataObject converter

### PR DESCRIPTION
**Pull request by rgmz**
Inspired by #201. 

This adds the ability to generate converters with the following conventions:

* Upper Camel Case (UpperCamelCase)
* Lower Camel Case (lowerCamelCase)
* Kebab Case (kebab-case)
* Snake Case (snake-case)

e.g. the following DataObject will generate a converter that serializes `exampleName` as `example-name`: 

```java
@DataObject(generateConverter = true, caseFormat = CaseFormat.KEBAB)
public class KebabCaseDataObject {
  private String exampleName;
  ...
}
```
In addition, the `@DataObjectProperty` annotation enables custom naming ~conventions~ on a per-field basis.

e.g. 

```java
  @DataObjectProperty("listOfFoo")
  private List<Object> fooList;
  @DataObjectProperty("map-of-bar")
  private Map<String, Object> barMap;
  @DataObjectProperty("string_of_baz")
  private String bazString;
```

-------

Unfortunately it was necessary to wrap `Case` with the `CaseFormat` enum as annotation defaults must be compile-time constant. (Funnily enough, `Case` used to be an [Enum](
https://github.com/vert-x3/vertx-codegen/blob/65f9f59308710a4c74c81439a59ec07b333d42d3/src/main/java/io/vertx/codegen/Case.java))

Not certain that "CaseFormat" is the [most apt name](https://www.martinfowler.com/bliki/TwoHardThings.html), however, so let me know if you have a better one. (Perhaps NamingConvention?)

### CODE REVIEW

**Comment by vietj** [comment]
looks good, there are few things I'd like to be changed.

I think we should keep one enum for cases, so can you modify the existing use a single enum (the one you created) instead of having two ? We will change the vertx code where it's used.

**Comment by rgmz** [comment]
The redundant enum pains me as well, however, I created a separate Case enum because:

>  Use classes instead of enum because MVEL does not like enum with abstract methods
> https://github.com/vert-x3/vertx-codegen/commit/fa84d57c1c64938c439e9e71181c659da2c6bccd

Is this no longer an issue?

**Comment by rgmz** [comment]
I've replaced `@DataObjectProperty(case: CaseFormat)` with a more pragmatic `@DataObjectProperty(value: String)` — akin to Jackson's 'JsonProperty'.

**Comment by vietj** [comment]
@rgmz it's not longer an issue we are moving away from MVEL, so please proceed

**Comment by vietj** [comment]
can we make two separate PR, one first for specifying the case of the data object entirely and another one after for enabling per property naming, that will allow to make the review of the PR easier.

**Comment by rgmz** [comment]
@vietj Done & done: #211 

(I removed the `@DataObjectProperty` changes from this branch; let me know if you want me to push a clean branch altogether with *only* those specific changes.)

**Comment by eutkin** [comment]
Hi all, any progress?

**Comment by vietj** [comment]
@eutkin actually no sorry, we could merge it I think

**Comment by rgmz** [comment]
@vietj It's been a while; give it another look (when you have the time) and let me know if there are any other changes you'd like made.

**Comment by eutkin** [comment]
@vietj, @rgmz i am waiting this feature at long ago :)

**Comment by vietj** [comment]
@eutkin good to know, let's target 3.7.1

**Comment by rgmz** [comment]
Re-created this PR as the original branch became orphaned and I couldn't fix the merge conflicts.

#259

**Comment by pendula95** [comment]
Why is this closed, PR has not been merged?

**Comment by vietj** [comment]
"Re-created this PR as the original branch became orphaned and I couldn't fix the merge conflicts."

**Comment by vietj** [comment]
so there is a new PR

**Comment by vietj** [comment]
we will likely merge it in 4 as we want to use data object for doing basic operations like database row mapping to data objects

**Pull request closed without merging**
