### PR TITLE
Made GeneratorHelper extensible

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Made GeneratorHelper extensible to use it for service proxy and web api service proxy.

### CODE REVIEW

**Comment by vietj** [comment]
why do we need this PR ? can't we reuse just `@ServiceProxy` ?

**Comment by vietj** [comment]
and use extra annotation

**Comment by slinkydeveloper** [comment]
I need it for test openapi service proxies

**Comment by vietj** [comment]
can't we reuse the ServiceProxy annotation since it's a service proxy as well ?

**Comment by slinkydeveloper** [comment]
It uses a different annotation for a different generator

**Comment by slinkydeveloper** [comment]
And we sad that want to move in next releases the ServiceProxy annotation outside vertx-codegen package

**Comment by vietj** [comment]
@slinkydeveloper not really possible to move this annotation out because it would create a split package issue

**Pull request merged**
