### PR TITLE
Added support for List<@DataObject> and Set<@DataObject>

### PR DESCRIPTION
**Pull request by mgardziejewski**
Added support for List<@DataObject> and Set<@DataObject> in result handler and method parameters

### CODE REVIEW

**Comment by vietj** [comment]
Hi, for such feature we need also:

- valid TCK tests for testing these in various languages: in  `io.vertx.codegen.testmodel` in the _src/tck/java_ dir
- at least one language implementation of this feature (JS, Groovy or Ruby) with corresponding TCK usage

**Comment by mgardziejewski** [comment]
Hi

1. I want to be sure that I understand your requirements correctly so the things
that I must do are:
        - add new types to test methods in
vertx-codegen/src/tck/java/io/vertx/codegen/testmodel/TestInterface.java
        - implement it in
vertx-codegen/src/tck/java/io/vertx/codegen/testmodel/TestInterfaceImpl.java
        - implement it in
vertx-lang-groovy/src/test/groovy/io/vertx/groovy/codegen/testmodel/TestInterface.groovy
        - add tests in
vertx-lang-groovy/src/test/groovy/io/vertx/lang/groovy/ApiTest.groovy

2. And what about pull request
https://github.com/vert-x3/vertx-service-proxy/pull/10 that is connected to this
one. Is there are some additional requirements for it?

Regards
Mariusz

**Comment by vietj** [comment]
hi,

1. correct, we need to be able to test this wrapping/unwrapping works correctly in all code generated languages

2. I need to review it, I will comment on this PR if there is something outstanding. But the lack of TCK I think is the primary issue for supporting this correctly

**Comment by vietj** [comment]
did you sign the Eclipse CLA ?

**Comment by vietj** [comment]
can you check this ? https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
